<?php

$version = '0.15.0';

file_put_contents(
    __DIR__ . '/syn.js',
    sprintf(
        <<<'JS'
        /**
         * Syn - Standalone Synthetic Event Library
         *
         * @generated by get-syn.php on %s
         *
         * @version %s
         * @copyright 2014 Bitovi
         * @license https://github.com/bitovi/syn/blob/master/LICENSE.md
         */
        
        %s
        JS,
        date('r'),
        $version,
        file_get_contents("https://www.unpkg.com/syn@$version/dist/global/syn.js")
    )
);

echo "Done.\n";
