name: CI

on:
  push:

env:
  DRIVER_URL: "http://localhost:4444/wd/hub"

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.browser == 'chrome' && matrix.selenium == '2.53.1' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
        browser: [ 'firefox', 'chrome' ]
        selenium: [ '2.53.1', '3', '4' ]
        allow_failures: [false]
        include:
          - selenium: '2.53.1'
            browser: 'chrome'
            allow_failures: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Start Selenium
        run: |
          mkdir -p ./logs
          SELENIUM_IMAGE=selenium/standalone-${{ matrix.browser }}:${{ matrix.selenium }} docker compose up --no-color &> ./logs/selenium.log &

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php }}"
          tools: composer
          ini-values: date.timezone=Europe/Berlin, error_reporting=-1, display_errors=On
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist --no-progress --ansi

      - name: Wait for selenium to start
        run: |
          curl --head -X GET --silent --show-error --retry 60 --retry-connrefused --retry-delay 1 http://172.18.0.2:4444

      - name: Run tests
        run: |
          export WEB_FIXTURES_BROWSER=${{ matrix.browser }}
          export DRIVER_URL=http://172.18.0.2:4444/wd/hub
          composer run tests -- -v --coverage-clover=coverage.xml --colors=always --testdox

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ !env.ACT }}
        with:
          files: coverage.xml

      - name: Archive logs artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs_php-${{ matrix.php }}_selenium-${{ matrix.selenium }}_${{ matrix.browser }}
          path: logs
